install! 'cocoapods', :deterministic_uuids => false
use_frameworks!

platform :ios, '14.0'

target 'TestPod_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestPod_Example
pod 'TestPODNingSDK',:git => 'https://github.com/ningguotong/TestPod_master.git'
pod 'SnapKit'


#pod 'GCDWebServer', '3.5.4'
#  pod 'Mux-Stats-AVPlayer', '3.1.0'
#  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '7.31.3'
#  pod 'GoogleWebRTC', '1.1.32000'
#  # pod 'WebRTC-arm64'
#  pod 'SwiftCentrifuge', '0.5.5'
#  pod 'SwiftProtobuf', '1.21.0'
end
