# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestPod_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestPod_Example
pod 'TestPODNingSDK',:git => 'https://github.com/ningguotong/TestPod_master.git'
pod 'SnapKit'
end
